"""Initial 0.3 schema

Revision ID: 45e1c95c045f
Revises: 
Create Date: 2018-03-22 10:14:42.430007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e1c95c045f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('slack_team_id', sa.String(length=16), nullable=False),
    sa.Column('strand_team_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='agentstatus'), nullable=False),
    sa.PrimaryKeyConstraint('slack_team_id')
    )
    op.create_table('bot',
    sa.Column('access_token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('agent_slack_team_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['agent_slack_team_id'], ['agent.slack_team_id'], ),
    sa.PrimaryKeyConstraint('agent_slack_team_id')
    )
    op.create_table('user',
    sa.Column('slack_user_id', sa.String(length=16), nullable=False),
    sa.Column('strand_user_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_slack_team_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['agent_slack_team_id'], ['agent.slack_team_id'], ),
    sa.PrimaryKeyConstraint('slack_user_id', 'agent_slack_team_id')
    )
    op.create_table('installation',
    sa.Column('access_token', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=256), nullable=False),
    sa.Column('installer_slack_user_id', sa.String(length=16), nullable=False),
    sa.Column('installer_agent_slack_team_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['installer_slack_user_id', 'installer_agent_slack_team_id'], ['user.slack_user_id', 'user.agent_slack_team_id'], ),
    sa.PrimaryKeyConstraint('installer_slack_user_id', 'installer_agent_slack_team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installation')
    op.drop_table('user')
    op.drop_table('bot')
    op.drop_table('agent')
    # ### end Alembic commands ###
